"""A hand-rolled discrete-event simulation of one dark store.

This is the defensible core of the twin. There is no SimPy: the event loop is a
binary heap (`heapq`) of timestamped events, processed in time order. It models

  * order arrivals as a non-homogeneous Poisson process (morning + evening
    peaks, generated by *thinning* a homogeneous process at the peak rate),
  * a picking station with a finite roster of pickers (an M/M/c-style queue),
  * rider dispatch with order batching and travel on the road graph
    (nearest-neighbour routing of a multi-drop trip, plus the return leg),

and reports the full delivery-time distribution, the SLA-breach rate, rider and
picker utilisation, and the realised per-order rider and picking cost. Those
realised costs feed the contribution-margin model, so the unit economics reflect
the actual queueing and routing dynamics, not a spreadsheet average.

Why a simulation and not a formula: the quantity that decides market entry is
counterfactual (the margin in a configuration that does not yet exist) and it is
driven by idle time, batching and SLA breach that a closed-form P&L cannot
capture. We calibrate the dense regime to a published loss-per-order before
trusting the sparse-regime extrapolation.
"""
from __future__ import annotations

import heapq
import math
from dataclasses import dataclass, field

import numpy as np

# Event kinds.
ARRIVAL = 0
PICK_DONE = 1
RIDER_RETURN = 2
FLUSH = 3


# A diurnal order-rate profile over a 16-hour operating day (08:00-24:00).
# Weights are relative; they get normalised so the integral equals the target
# orders/day. Two peaks: a late-morning bump and a dominant evening peak.
DEFAULT_HOURLY_WEIGHTS = np.array(
    [0.5, 0.8, 1.0, 0.9, 0.7, 0.6, 0.6, 0.7, 1.0, 1.4, 1.8, 2.0, 1.7, 1.2, 0.9, 0.6]
)


@dataclass
class SimConfig:
    """All knobs of the dark-store simulation."""

    orders_per_day: float = 340.0
    open_hours: float = 16.0
    n_pickers: int = 2
    n_riders: int = 6
    batch_target: int = 1          # max orders per rider trip (1 = no batching)
    max_batch_wait_min: float = 4.0  # how long a picked order waits to fill a batch
    mean_pick_min: float = 3.5     # mean picking service time
    pick_cv: float = 0.4           # coefficient of variation of pick time (lognormal)
    mean_drop_km: float = 1.1      # mean store->customer road distance
    rider_speed_kmph: float = 20.0
    handover_min: float = 2.0      # per-drop handover time
    sla_min: float = 15.0          # delivery SLA
    rider_wage_per_day: float = 700.0
    picker_wage_per_day: float = 750.0
    hourly_weights: np.ndarray = field(default=None)

    def weights(self) -> np.ndarray:
        w = self.hourly_weights if self.hourly_weights is not None else DEFAULT_HOURLY_WEIGHTS
        return np.asarray(w, dtype=float)


@dataclass
class SimResult:
    """Aggregated outputs over all replications."""

    orders_arrived: float
    orders_delivered: float
    mean_delivery_min: float
    p90_delivery_min: float
    sla_breach_rate: float
    rider_utilization: float
    picker_utilization: float
    mean_pick_wait_min: float
    mean_dispatch_wait_min: float
    rider_cost_per_order: float
    picking_cost_per_order: float

    def as_dict(self) -> dict[str, float]:
        return self.__dict__.copy()


class _Order:
    __slots__ = ("id", "arrival", "picked", "dispatched", "delivered", "drop_km")

    def __init__(self, oid: int, arrival: float, drop_km: float):
        self.id = oid
        self.arrival = arrival
        self.picked = None
        self.dispatched = None
        self.delivered = None
        self.drop_km = drop_km


class DarkStoreSim:
    """One dark store, one or more simulated days."""

    def __init__(self, cfg: SimConfig, seed: int = 0):
        self.cfg = cfg
        self.seed = seed

    # ----- arrivals: non-homogeneous Poisson via thinning -----
    def _generate_arrivals(self, rng: np.random.Generator) -> list[float]:
        cfg = self.cfg
        horizon = cfg.open_hours * 60.0
        w = cfg.weights()
        # Per-hour arrival rate (orders/min) such that the day integrates to target.
        hours = len(w)
        hour_len = horizon / hours
        # mean orders in hour h proportional to w[h]; sum == orders_per_day
        hourly_orders = cfg.orders_per_day * w / w.sum()
        rate_per_min = hourly_orders / hour_len  # length `hours`
        lam_max = rate_per_min.max()
        if lam_max <= 0:
            return []
        # Homogeneous candidates at lam_max, thin by accept prob rate(t)/lam_max.
        times: list[float] = []
        t = 0.0
        while True:
            t += rng.exponential(1.0 / lam_max)
            if t >= horizon:
                break
            h = min(hours - 1, int(t // hour_len))
            if rng.random() < rate_per_min[h] / lam_max:
                times.append(t)
        return times

    def _pick_time(self, rng: np.random.Generator) -> float:
        # Lognormal service time with the configured mean and CV.
        cfg = self.cfg
        mu_log = math.log(cfg.mean_pick_min) - 0.5 * math.log(1 + cfg.pick_cv**2)
        sigma_log = math.sqrt(math.log(1 + cfg.pick_cv**2))
        return float(rng.lognormal(mu_log, sigma_log))

    def _drop_km(self, rng: np.random.Generator) -> float:
        # Distance to customer: heavier toward the mean, light tail. Gamma keeps
        # it positive with a controllable spread.
        cfg = self.cfg
        shape = 4.0
        scale = cfg.mean_drop_km / shape
        return float(rng.gamma(shape, scale))

    def _route_minutes(self, drops: list[float]) -> tuple[float, list[float]]:
        """Multi-drop trip time. drops = store->customer road km for each order.

        Nearest-neighbour ordering of the drops (closest first), travel at the
        rider speed, a handover at each stop, and a return leg back to the store.
        Returns (total_trip_minutes, per_order_delivered_offset_minutes).
        """
        cfg = self.cfg
        speed_km_per_min = cfg.rider_speed_kmph / 60.0
        order_idx = sorted(range(len(drops)), key=lambda k: drops[k])
        prev = 0.0
        t = 0.0
        delivered_offset = [0.0] * len(drops)
        for k in order_idx:
            leg = abs(drops[k] - prev)  # along a radial corridor approximation
            t += leg / speed_km_per_min + cfg.handover_min
            delivered_offset[k] = t
            prev = drops[k]
        # return leg to store
        t += prev / speed_km_per_min
        return t, delivered_offset

    def _run_once(self, seed: int) -> dict:
        cfg = self.cfg
        rng = np.random.default_rng(seed)
        horizon = cfg.open_hours * 60.0

        arrivals = self._generate_arrivals(rng)
        heap: list[tuple] = []
        seq = 0

        def push(time, kind, payload):
            nonlocal seq
            heapq.heappush(heap, (time, seq, kind, payload))
            seq += 1

        orders: list[_Order] = []
        for at in arrivals:
            o = _Order(len(orders), at, self._drop_km(rng))
            orders.append(o)
            push(at, ARRIVAL, o)

        free_pickers = cfg.n_pickers
        idle_riders = cfg.n_riders
        pick_queue: list[_Order] = []
        staging: list[_Order] = []

        picker_busy_min = 0.0
        rider_busy_min = 0.0

        def try_pick(now):
            nonlocal free_pickers, picker_busy_min
            while free_pickers > 0 and pick_queue:
                o = pick_queue.pop(0)
                free_pickers -= 1
                dur = self._pick_time(rng)
                picker_busy_min += dur
                o.picked = now + dur
                push(now + dur, PICK_DONE, o)

        def try_dispatch(now):
            """Dispatch whenever a rider is idle and the front of staging is
            either part of a full batch or has waited out its batching window.

            Batching wakeups are handled by one-shot FLUSH events scheduled per
            order at PICK_DONE (below), so this never schedules events itself and
            the FLUSH count is bounded by the number of orders.
            """
            nonlocal idle_riders, rider_busy_min
            while idle_riders > 0 and staging:
                ready = len(staging) >= cfg.batch_target
                waited = (now - staging[0].picked) >= cfg.max_batch_wait_min
                if not (ready or waited):
                    break
                batch = [staging.pop(0) for _ in range(min(cfg.batch_target, len(staging)))]
                idle_riders -= 1
                trip_min, offsets = self._route_minutes([o.drop_km for o in batch])
                rider_busy_min += trip_min
                for o, off in zip(batch, offsets):
                    o.dispatched = now
                    o.delivered = now + off
                push(now + trip_min, RIDER_RETURN, None)

        while heap:
            now, _, kind, payload = heapq.heappop(heap)
            if kind == ARRIVAL:
                pick_queue.append(payload)
                try_pick(now)
            elif kind == PICK_DONE:
                free_pickers += 1
                staging.append(payload)
                # One-shot wakeup so this order cannot wait past the batch window.
                push(payload.picked + cfg.max_batch_wait_min, FLUSH, None)
                try_pick(now)
                try_dispatch(now)
            elif kind == RIDER_RETURN:
                idle_riders += 1
                try_dispatch(now)
            elif kind == FLUSH:
                try_dispatch(now)

        delivered = [o for o in orders if o.delivered is not None]
        delivery_times = np.array([o.delivered - o.arrival for o in delivered])
        # Time from arrival to picking completion (queue + service) and time a
        # picked order waits in staging for a rider; both retained on the order.
        dispatch_waits = np.array([o.dispatched - o.picked for o in delivered])
        in_pipeline_waits = np.array([o.picked - o.arrival for o in delivered])

        open_min = horizon
        return {
            "arrived": len(orders),
            "delivered": len(delivered),
            "delivery_times": delivery_times,
            "dispatch_waits": dispatch_waits,
            "pick_pipeline": in_pipeline_waits,
            "picker_busy_min": picker_busy_min,
            "rider_busy_min": rider_busy_min,
            "picker_capacity_min": cfg.n_pickers * open_min,
            "rider_capacity_min": cfg.n_riders * open_min,
        }

    def run(self, replications: int = 30) -> SimResult:
        cfg = self.cfg
        agg_delivery: list[np.ndarray] = []
        agg_dispatch: list[np.ndarray] = []
        agg_pipeline: list[np.ndarray] = []
        arrived = delivered = 0.0
        picker_busy = rider_busy = 0.0
        picker_cap = rider_cap = 0.0
        for r in range(replications):
            out = self._run_once(self.seed + r)
            arrived += out["arrived"]
            delivered += out["delivered"]
            if len(out["delivery_times"]):
                agg_delivery.append(out["delivery_times"])
                agg_dispatch.append(out["dispatch_waits"])
                agg_pipeline.append(out["pick_pipeline"])
            picker_busy += out["picker_busy_min"]
            rider_busy += out["rider_busy_min"]
            picker_cap += out["picker_capacity_min"]
            rider_cap += out["rider_capacity_min"]

        all_delivery = np.concatenate(agg_delivery) if agg_delivery else np.array([0.0])
        all_dispatch = np.concatenate(agg_dispatch) if agg_dispatch else np.array([0.0])
        all_pipeline = np.concatenate(agg_pipeline) if agg_pipeline else np.array([0.0])

        delivered_per_day = delivered / replications
        rider_util = rider_busy / rider_cap if rider_cap else 0.0
        picker_util = picker_busy / picker_cap if picker_cap else 0.0

        rider_cost_day = cfg.n_riders * cfg.rider_wage_per_day
        picker_cost_day = cfg.n_pickers * cfg.picker_wage_per_day
        rider_cost_per_order = (
            rider_cost_day / delivered_per_day if delivered_per_day > 0 else float("inf")
        )
        picking_cost_per_order = (
            picker_cost_day / delivered_per_day if delivered_per_day > 0 else float("inf")
        )

        return SimResult(
            orders_arrived=arrived / replications,
            orders_delivered=delivered_per_day,
            mean_delivery_min=float(all_delivery.mean()),
            p90_delivery_min=float(np.percentile(all_delivery, 90)),
            sla_breach_rate=float((all_delivery > cfg.sla_min).mean()),
            rider_utilization=rider_util,
            picker_utilization=picker_util,
            mean_pick_wait_min=float(all_pipeline.mean()),
            mean_dispatch_wait_min=float(all_dispatch.mean()),
            rider_cost_per_order=rider_cost_per_order,
            picking_cost_per_order=picking_cost_per_order,
        )
